name: Commit Stage - Build Image

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      SCW_DOCKER_REGISTRY:
        required: true
      SCW_TOKEN:
        required: true

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build The Docker Container
        run: docker build -t ${{ secrets.SCW_DOCKER_REGISTRY }}/${{ inputs.image }}:${{ inputs.version }} src

      - name: Login to docker
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.SCW_DOCKER_REGISTRY }}
          username: ${{ secrets.SCW_TOKEN }}
          password: ${{ secrets.SCW_TOKEN }}

      - name: Push The Docker Container
        run: docker push ${{ secrets.SCW_DOCKER_REGISTRY }}/${{ inputs.image }}:${{ inputs.version }}
