name: Commit Stage

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Image
    uses: ./.github/workflows/commit-stage--build-image.yml
    with:
      image: ${{ github.event.repository.name }}
      version: ${{ github.sha }}
    secrets:
      SCW_DOCKER_REGISTRY: ${{ secrets.SCW_DOCKER_REGISTRY }}
      SCW_TOKEN: ${{ secrets.SCW_TOKEN }}
