name: Deployment Stage

on:
  workflow_run:
    workflows: ["Commit Stage"]
    types: [completed]

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/deployment-stage--terraform-apply.yml
    with:
      image_version: ${{ github.sha }}
      environment: PRODUCTION
    secrets:
      scw_access_key: ${{ secrets.SCW_ACCESS_KEY }}
      scw_project_id: ${{ secrets.SCW_PROJECT_ID }}
      scw_secret_key: ${{ secrets.SCW_SECRET_KEY }}
